### ISSUE TITLE
missing 65536 bytes in zipfile

### ISSUE THREAD

**Issue by ghost** [johankj/convert-crx-to-zip#1]
1. Download crx like chromium does(**EDIT:** or maybe this is uMatrix? **EDIT2:** nah, should be chromium): http://redirector.gvt1.com/edgedl/release2/C6dTTRxWf3I/7.54_all_easylist.crx
2. go https://johankj.github.io/convert-crx-to-zip/
3. autodownloads .zip after conversion
4.
```bash
$ unzip -lv 7.54_all_easylist.zip
Archive:  7.54_all_easylist.zip
error [7.54_all_easylist.zip]:  missing 65536 bytes in zipfile
  (attempting to process anyway)
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 1627262  Defl:N   341167  79% 2017-04-11 10:28 46d2acba  Filtering Rules
   24623  Defl:N     7925  68% 2017-04-11 10:28 d4672162  LICENSE
     113  Defl:N       94  17% 2017-04-11 10:28 b087dfc7  manifest.json
--------          -------  ---                            -------
 1651998           349186  79%                            3 files
```

```
-rw-r--r--  1 xftroxgpx xftroxgpx 350120 27.04.2017 14:46 7.54_all_easylist.crx
-rw-r--r--  1 xftroxgpx xftroxgpx 284018 27.04.2017 14:47 7.54_all_easylist.zip
```

**Comment by ghost** [comment]
It actually works ok for this 6meg crx (that chromium is downloading)
$ wget 'https://redirector.gvt1.com/crx/blobs/QwAAAHF3InbmK-wFIemaY3I3BCMFmcli-ojPxrss8OnaeWj-aM94KnUfZllIB6iNgvIzbiyOQEq29-MqzDnS_lFrvqud57a69nl2Pj1Qy2siwmJ-AMZSmuXBvTcInJAMMfStC_pNirYxGyjQGw/extension_0_57_44_2492.crx'

**Comment by ghost** [comment]
and this one's zip is 0 bytes :D
http://redirector.gvt1.com/edgedl/release2/emh61y0oo97qda7u1zli4yjqg02ne9itvhpj1gwr8t3z2khxsa5n0s7ec2jqoruwi6k323zs9rrspz8rkp9knxodt8diww7tv6r/8_linux_fileTypePolicies.crx

**Comment by ghost** [comment]
Got another like OP:
$ wget https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP35Av6_uD2R0shIWqC2XwPmpwrDdH5TKyq_6MWRGfvCXV3f-8g220oUjAO-JvMYG2m5CSvsx6cHch05zQS7ZbtrAMZSmuWMzK-Yj7NpgCxtqGhyTFveAvi-IQ/extension_7.crx

```
$ unzip -lv extension_7.zip
Archive:  extension_7.zip
error [extension_7.zip]:  missing 65536 bytes in zipfile
  (attempting to process anyway)
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     338  Defl:N      222  34% 2015-08-28 15:16 1af227a1  manifest.json
  674082  Defl:N   674292   0% 2015-08-28 15:16 d3c8661b  _platform_specific/all/ev_hashes_whitelist.bin
    1553  Defl:N     1110  29% 2015-08-28 15:16 485d1593  _metadata/verified_contents.json
--------          -------  ---                            -------
  675973           675624   0%                            3 files
```

**Comment by ghost** [comment]
meh here's the full chrome://net-export  if anyone might find this useful at some point heh
[netexport.zip](https://github.com/johankj/convert-crx-to-zip/files/961636/netexport.zip)
I only had uMatrix extension installed, otherwise pristine chromium environment, I suppose.

**Comment by johankj** [comment]
Thanks for the very detailed feedback. I think it should be fixed now.

**Comment by ghost** [comment]
Thank you! Much appreciated.
Cheers!

**Comment by ghost** [comment]
Does the web [interface](https://johankj.github.io/convert-crx-to-zip/convert.js) only get updated if you update the [gh-pages](https://github.com/johankj/convert-crx-to-zip/tree/gh-pages) branch? I've never tried using github pages.

**Comment by johankj** [comment]
Indeed it does. Thanks for reminding me. 😅

**Comment by ghost** [comment]
Cool! Thank you for allocating some of your time to fixing this!
I tested and can confirm the OP issue is now fixed.
Cheers my friend! :)
